version: '2'
services:
  db:
    build: ./mongo
    image: amubtdx/battlecsn_mongo
    expose:
      - "27017"
    ports:
      - "28017:28017"
      - "27017:27017"
    networks:
      - net
  web:
    build: ./tomcat
    image: amubtdx/battlecsn_tomcat
    environment:
      CATALINA_OPTS: "-Ddb.host=db"
    depends_on:
      - db
    ports:
      - "8084:8080"
    networks:
      - net

networks:
  net:
    driver: bridge
